### ISSUE TITLE
About reasoning segmentation task

### ISSUE THREAD

**Issue by zhengyuan-xie** [wusize/F-LMM#10]
Hi, thank you for your great work! I wonder whether F-LMM can be used for reasoning segmentation(It seems that F-LMM can only understand explicit descriptions for segmentation). Thanks!

**Comment by wusize** [comment]
Hi! Thank you for raising this interesting question. To perform reasoning segmentation, F-LMM can first let the LMM produce an answer and then ground the content of the answer (just like what we have done in visual cot). I will try adding this feature when I have time.
