### ISSUE TITLE
Versions about mmcv,mmseg,...

### ISSUE THREAD

**Issue by jxliuwork** [wusize/F-LMM#12]
Could youm please shares the versions of the  packages, such as mmcv, mmsegmentation,...

**Comment by jxliuwork** [comment]
and xtuner,

**Comment by zhengyuan-xie** [comment]
Hi, did you successfully install the environment?

**Comment by xyzjin** [comment]
> Hi, did you successfully install the environment?

yes

**Comment by zhengyuan-xie** [comment]
> > Hi, did you successfully install the environment?
> 
> yes

Hi, could you provide details of the environment? Many thanks.

**Comment by xyzjin** [comment]
mmcv 2.1.0
mmseg 1.2.2

**Comment by zhengyuan-xie** [comment]
Thanks a lot!
