### ISSUE TITLE
The links for model checkpoints are down

### ISSUE THREAD

**Issue by mxh1999** [wusize/F-LMM#13]
Thank you for your great work!
Could you please update the links for `data/cot` and model checkpoints? They are all down now.
Thanks a lot!

**Comment by wusize** [comment]
Hi! I am uploading files to [onedrive](https://entuedu-my.sharepoint.com/:f:/g/personal/size001_e_ntu_edu_sg/EvLw4iR7tQpLtMTLOJ5lo6sBYhVO7LXYOlMJAFBvxrWJHA?e=JtChlA). Please wait for two hours before I finish.

**Comment by mxh1999** [comment]
Thanks a lot!
